#%RAML 1.0 Library
usage:


types:


  AccountData:
    type: object
    properties:
      account_id: string
      bban: string
      iban: string
      account_name: string
      bank_num: string
      upic: string
      bank_name:  string
      country:  string
      account_balance:  string
      currency: string
      open_date:  
        type: datetime
        required: false
