sfdc:
  susername: "sam@cleanorg.com"
  username: "bruno@cleanorg.com"
  musername: "michael@cleanorg.com"
  username2: "michael.berger@tmf19.demo"
  spassword: "SSBSF1990$"
  password: "Mulesoft2021#"
  mpassword: "SnapChat1821"
  stoken: "vkSGcT8c47tQwZDcs8FoJ0Ur"
  token: "ykmrctH7ke8bqs0qOTiM2iJF"
  mtoken: "CP1Tww08BWm0eJZgsnKvHAjQI"
  token2: "0K7HqrXi6ntgiyPo7Lo0TBj2r"
  sfurl: "https://na91.salesforce.com/"