sfdc:
  susername: "sam@cleanorg.com"
  username: "bruno@cleanorg.com"
  musername: "michael@cleanorg.com"
  username2: "michael.berger@tmf19.demo"
  spassword: 
  password: 
  mpassword:
  stoken: 
  token: 
  mtoken: 
  token2:
  sfurl: "https://na91.salesforce.com/"
