#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/58d5726f-acc5-43df-be21-bbf9fb6dca4a # 
title: IntraBankNationalXfer

uses:
  data_types: exchange_modules/13d9279c-5e29-4b40-b236-56641f4e0737/paymentorder_banking_datatypes/1.0.1/payment_banking_datatypes.raml

/IntraBankNationalXfer:
  post:
    body: 
      application/json:
        type: data_types.Payment
        example: !include Samples/Payment_sample_2.json

    responses: 
      200:
        body: 
          application/json:
            type: data_types.PaymentResponse
            example:  !include  Samples/PaymentResponse_sample.json
    
      