#%RAML 1.0 Library
usage:

types:
  NotificationRequest:
    type: object
    properties: 
      DebtorBank: string
      DebtorAcct:  string
      CreditorBank: string
      CreditorAcct: string
      Sum:  number
      Currency: string